#!/bin/bash
hosts=( "@" "subdomain1" "subdomain2" "subdomain3" )
domain="domain.com"
password="your-dns-password"

hosts_updated=""
hosts_unchanged=""

# Fetch your WAN IP address
new_ip=$(curl -s http://dynamicdns.park-your-domain.com/getip)

for host in ${hosts[*]}
do
        if [[ $host == "@" ]]; then
                fulldomain=$domain
        elif [[ $host != "@" ]]; then
                fulldomain=$host.$domain
        fi

        # Check if the A record is the same as your current WAN IP, if it is just continue with the next host
        current_ip=$(dig $fulldomain @8.8.8.8 +short)
        if [[ $new_ip == $current_ip ]]; then
                hosts_unchanged+="${fulldomain}\n"
                continue
        fi

        # Send CURL and store the response
        response=$(curl -s "https://dynamicdns.park-your-domain.com/update?host=$host&domain=$domain&password=$password&ip=$new_ip")
        
        # Check if there's errors in the response
        regex="<ErrCount>([0-1])<\/ErrCount>"
        if [[ $response =~ $regex ]]; then
                if [[ ${BASH_REMATCH[1]} == "0" ]]; then
                        hosts_updated+="${fulldomain}\n"

                elif [[ ${BASH_REMATCH[1]} == "1" ]]; then
                        /usr/local/emhttp/webGui/scripts/notify -e "DDNS Namecheap" -s "DNS Update Error ${fulldomain}" -i "warning" -m "An error was encountered when trying to update ${fulldomain}, the response was:\n${response}" -t
                fi
        fi
done

# If any hosts have been updated, send an Unraid notification. If no hosts have been updated, the script exits silently.
if [[ ! -z "$hosts_updated" ]]; then
        message="The following hosts just had their DNS updated with IP ${new_ip}:\n${hosts_updated}"
	
        # If any of the hosts were unchanged, mention them in the message
        if [[ ! -z "$hosts_unchanged" ]]; then
                message+="\nThe following hosts were left unchanged:\n${hosts_unchanged}"
        fi

        /usr/local/emhttp/webGui/scripts/notify -e "DDNS Namecheap" -s "DNS Updated: ${new_ip}" -m $message -t
fi